import {GTADLC} from "./ungrouped";
import {FiveVWeapon, FiveVWeaponComponent, FiveVWeaponType} from "../@types/weapon";

export const FiveVWeapons : FiveVWeapon[] = [
    {name: "Unarmed", type: FiveVWeaponType.UNARMED, Hash: "WEAPON_UNARMED", Model_Hash_Key: "", DLC: GTADLC.CORE, Description: "", Components: []},
    {name: "Knuckle Duster", type: FiveVWeaponType.UNARMED, Hash: "WEAPON_KNUCKLE", Model_Hash_Key: "", DLC: GTADLC.MPLUXE2, Description: "Perfect for knocking out gold teeth, or as a gift to the trophy partner who has everything. Part of The Ill-Gotten Gains Update Part 2.",
        Components: [
            { name: "Base Model", Hash_Key: "COMPONENT_KNUCKLE_VARMOD_BASE", Hash: "0xF3462F33" },
            { name: "The Pimp", Hash_Key: "COMPONENT_KNUCKLE_VARMOD_PIMP", Hash: "0xC613F685" },
            { name: "The Ballas", Hash_Key: "COMPONENT_KNUCKLE_VARMOD_BALLAS", Hash: "0xEED9FD63" },
            { name: "The Hustler", Hash_Key: "COMPONENT_KNUCKLE_VARMOD_DOLLAR", Hash: "0x50910C31" },
            { name: "The Rock", Hash_Key: "COMPONENT_KNUCKLE_VARMOD_DIAMOND", Hash: "0x9761D9DC" },
            { name: "The Hater", Hash_Key: "COMPONENT_KNUCKLE_VARMOD_HATE", Hash: "0x7DECFE30" },
            { name: "The Lover", Hash_Key: "COMPONENT_KNUCKLE_VARMOD_LOVE", Hash: "0x3F4E8AA6" },
            { name: "The Player", Hash_Key: "COMPONENT_KNUCKLE_VARMOD_PLAYER", Hash: "0x8B808BB" },
            { name: "The King", Hash_Key: "COMPONENT_KNUCKLE_VARMOD_KING", Hash: "0xE28BABEF" },
            { name: "The Vagos", Hash_Key: "COMPONENT_KNUCKLE_VARMOD_VAGOS", Hash: "0x7AF3F785" },
        ]},
    // MACHINE GUN MG
    {name: "MG", type: FiveVWeaponType.MACHINEGUN, Hash: "WEAPON_MG", Model_Hash_Key: "w_mg_mg", DLC: GTADLC.CORE, Description: "General purpose machine gun that combines rugged design with dependable performance. Long range penetrative power. Very effective against large groups.",
        Components: [// MG
            { name: "Default Clip", Hash_Key: "COMPONENT_MG_CLIP_01", Hash: "0xF434EF84" },
            { name: "Extended Clip", Hash_Key: "COMPONENT_MG_CLIP_02", Hash: "0x82158B47" },
            { name: "Scope", Hash_Key: "COMPONENT_AT_SCOPE_SMALL_02", Hash: "0x3C00AFED" },
            { name: "Yusuf Amir Luxury Finish", Hash_Key: "COMPONENT_MG_VARMOD_LOWRIDER", Hash: "0xD6DABABE" },
        ]},
    {name: "Combat MG", type: FiveVWeaponType.MACHINEGUN, Hash: "WEAPON_COMBATMG", Model_Hash_Key: "w_mg_combatmg", DLC: GTADLC.CORE, Description: "Lightweight, compact machine gun that combines excellent maneuverability with a high rate of fire to devastating effect.",
        Components: [// Combat MG
            { name: "Default Clip", Hash_Key: "COMPONENT_COMBATMG_CLIP_01", Hash: "0xE1FFB34A" },
            { name: "Extended Clip", Hash_Key: "COMPONENT_COMBATMG_CLIP_02", Hash: "0xD6C59CD6" },
            { name: "Scope", Hash_Key: "COMPONENT_AT_SCOPE_MEDIUM", Hash: "0xA0D89C42" },
            { name: "Grip", Hash_Key: "COMPONENT_AT_AR_AFGRIP", Hash: "0x3C00AFED" },
            { name: "Yusuf Amir Luxury Finish", Hash_Key: "COMPONENT_COMBATMG_VARMOD_LOWRIDER", Hash: "0x92FECCDD" },
        ]},
    {name: "Combat MG Mk II", type: FiveVWeaponType.MACHINEGUN, Hash: "WEAPON_COMBATMG_MK2", Model_Hash_Key: "w_mg_combatmgmk2", DLC: GTADLC.MPGUNRUNNING, Description: "You can never have too much of a good thing: after all, if the first shot counts, then the next hundred or so must count for double.",
    Components: [// Combat MG Mk II
        { name: "Default Clip", Hash_Key: "COMPONENT_COMBATMG_MK2_CLIP_01", Hash: "0x492B257C" },
        { name: "Extended Clip", Hash_Key: "COMPONENT_COMBATMG_MK2_CLIP_02", Hash: "0x17DF42E9" },
        { name: "Tracer Rounds", Hash_Key: "COMPONENT_COMBATMG_MK2_CLIP_TRACER", Hash: "0xF6649745" },
        { name: "Incendiary Rounds", Hash_Key: "COMPONENT_COMBATMG_MK2_CLIP_INCENDIARY", Hash: "0xC326BDBA" },
        { name: "Armor Piercing Rounds", Hash_Key: "COMPONENT_COMBATMG_MK2_CLIP_ARMORPIERCING", Hash: "0x29882423" },
        { name: "Full Metal Jacket Rounds", Hash_Key: "COMPONENT_COMBATMG_MK2_CLIP_FMJ", Hash: "0x57EF1CC8" },
        { name: "Grip", Hash_Key: "COMPONENT_AT_AR_AFGRIP_02", Hash: "0x9D65907A" },
        { name: "Holographic Sight", Hash_Key: "COMPONENT_AT_SIGHTS", Hash: "0x420FD713" },
        { name: "Medium Scope", Hash_Key: "COMPONENT_AT_SCOPE_SMALL_MK2", Hash: "0x3F3C8181" },
        { name: "Large Scope", Hash_Key: "COMPONENT_AT_SCOPE_MEDIUM_MK2", Hash: "0xC66B6542" },
        { name: "Flat Muzzle Brake", Hash_Key: "COMPONENT_AT_MUZZLE_01", Hash: "0xB99402D4" },
        { name: "Tactical Muzzle Brake", Hash_Key: "COMPONENT_AT_MUZZLE_02", Hash: "0xC867A07B" },
        { name: "Fat-End Muzzle Brake", Hash_Key: "COMPONENT_AT_MUZZLE_03", Hash: "0xDE11CBCF" },
        { name: "Precision Muzzle Brake", Hash_Key: "COMPONENT_AT_MUZZLE_04", Hash: "0xEC9068CC" },
        { name: "Heavy Duty Muzzle Brake", Hash_Key: "COMPONENT_AT_MUZZLE_05", Hash: "0x2E7957A" },
        { name: "Slanted Muzzle Brake", Hash_Key: "COMPONENT_AT_MUZZLE_06", Hash: "0x347EF8AC" },
        { name: "Split-End Muzzle Brake", Hash_Key: "COMPONENT_AT_MUZZLE_07", Hash: "0x4DB62ABE" },
        { name: "Default Barrel", Hash_Key: "COMPONENT_AT_MG_BARREL_01", Hash: "0xC34EF234" },
        { name: "Heavy Barrel", Hash_Key: "COMPONENT_AT_MG_BARREL_02", Hash: "0xB5E2575B" },
        { name: "Digital Camo", Hash_Key: "COMPONENT_COMBATMG_MK2_CAMO", Hash: "0x4A768CB5" },
        { name: "Brushstroke Camo", Hash_Key: "COMPONENT_COMBATMG_MK2_CAMO_02", Hash: "0xCCE06BBD" },
        { name: "Woodland Camo", Hash_Key: "COMPONENT_COMBATMG_MK2_CAMO_03", Hash: "0xBE94CF26" },
        { name: "Skull", Hash_Key: "COMPONENT_COMBATMG_MK2_CAMO_04", Hash: "0x7609BE11" },
        { name: "Sessanta Nove", Hash_Key: "COMPONENT_COMBATMG_MK2_CAMO_05", Hash: "0x48AF6351" },
        { name: "Perseus", Hash_Key: "COMPONENT_COMBATMG_MK2_CAMO_06", Hash: "0x9186750A" },
        { name: "Leopard", Hash_Key: "COMPONENT_COMBATMG_MK2_CAMO_07", Hash: "0x84555AA8" },
        { name: "Zebra", Hash_Key: "COMPONENT_COMBATMG_MK2_CAMO_08", Hash: "0x1B4C088B" },
        { name: "Geometric", Hash_Key: "COMPONENT_COMBATMG_MK2_CAMO_09", Hash: "0xE046DFC" },
        { name: "Boom!", Hash_Key: "COMPONENT_COMBATMG_MK2_CAMO_10", Hash: "0x28B536E" },
        { name: "Patriotic", Hash_Key: "COMPONENT_COMBATMG_MK2_CAMO_IND_01", Hash: "0xD703C94D" }
    ]},
    {name: "Unholy Hellbringer", type: FiveVWeaponType.MACHINEGUN, Hash: "WEAPON_RAYCARBINE", Model_Hash_Key: "w_ar_srifle", DLC: GTADLC.MPCHRISTMAS2018, Description: "Republican Space Ranger Special. If you want to turn a little green man into little green goo, this is the only American way to do it.",
    Components: []},
    {name: "Gusenberg Sweeper", type: FiveVWeaponType.MACHINEGUN, Hash: "WEAPON_GUSENBERG", Model_Hash_Key: "w_sb_gusenberg", DLC: GTADLC.MPVALENTINES, Description: "Complete your look with a Prohibition gun. Looks great being fired from an Albany Roosevelt or paired with a pinstripe suit. Part of the Valentine's Day Massacre Special.",
    Components: [// Gusenberg Sweeper
        { name: "Default Clip", Hash_Key: "COMPONENT_GUSENBERG_CLIP_01", Hash: "0x1CE5A6A5" },
        { name: "Extended Clip", Hash_Key: "COMPONENT_GUSENBERG_CLIP_02", Hash: "0xEAC8C270" },]},
    // RIFLE
    {name: "Assault Rifle Mk II", type: FiveVWeaponType.RIFLE, Hash: "WEAPON_ASSAULTRIFLE_MK2", Model_Hash_Key: "w_ar_assaultriflemk2", DLC: GTADLC.MPGUNRUNNING, Description: "The definitive revision of an all-time classic: all it takes is a little work, and looks can kill after all.",
    Components: [// Assault Rifle Mk II
        { name: "Default Clip", Hash_Key: "COMPONENT_ASSAULTRIFLE_MK2_CLIP_01", Hash: "0x8610343F" },
        { name: "Extended Clip", Hash_Key: "COMPONENT_ASSAULTRIFLE_MK2_CLIP_02", Hash: "0xD12ACA6F" },
        { name: "Tracer Rounds", Hash_Key: "COMPONENT_ASSAULTRIFLE_MK2_CLIP_TRACER", Hash: "0xEF2C78C1" },
        { name: "Incendiary Rounds", Hash_Key: "COMPONENT_ASSAULTRIFLE_MK2_CLIP_INCENDIARY", Hash: "0xFB70D853" },
        { name: "Armor Piercing Rounds", Hash_Key: "COMPONENT_ASSAULTRIFLE_MK2_CLIP_ARMORPIERCING", Hash: "0xA7DD1E58" },
        { name: "Full Metal Jacket Rounds", Hash_Key: "COMPONENT_ASSAULTRIFLE_MK2_CLIP_FMJ", Hash: "0x63E0A098" },
        { name: "Grip", Hash_Key: "COMPONENT_AT_AR_AFGRIP_02", Hash: "0x9D65907A" },
        { name: "Flashlight", Hash_Key: "COMPONENT_AT_AR_FLSH", Hash: "0x7BC4CDDC" },
        { name: "Holographic Sight", Hash_Key: "COMPONENT_AT_SIGHTS", Hash: "0x420FD713" },
        { name: "Small Scope", Hash_Key: "COMPONENT_AT_SCOPE_MACRO_MK2", Hash: "0x49B2945" },
        { name: "Medium Scope", Hash_Key: "COMPONENT_AT_SCOPE_MEDIUM_MK2", Hash: "0xC66B6542" },
        { name: "Suppressor", Hash_Key: "COMPONENT_AT_AR_SUPP_02", Hash: "0xA73D4664" },
        { name: "Flat Muzzle Brake", Hash_Key: "COMPONENT_AT_MUZZLE_01", Hash: "0xB99402D4" },
        { name: "Tactical Muzzle Brake", Hash_Key: "COMPONENT_AT_MUZZLE_02", Hash: "0xC867A07B" },
        { name: "Fat-End Muzzle Brake", Hash_Key: "COMPONENT_AT_MUZZLE_03", Hash: "0xDE11CBCF" },
        { name: "Precision Muzzle Brake", Hash_Key: "COMPONENT_AT_MUZZLE_04", Hash: "0xEC9068CC" },
        { name: "Heavy Duty Muzzle Brake", Hash_Key: "COMPONENT_AT_MUZZLE_05", Hash: "0x2E7957A" },
        { name: "Slanted Muzzle Brake", Hash_Key: "COMPONENT_AT_MUZZLE_06", Hash: "0x347EF8AC" },
        { name: "Split-End Muzzle Brake", Hash_Key: "COMPONENT_AT_MUZZLE_07", Hash: "0x4DB62ABE" },
        { name: "Default Barrel", Hash_Key: "COMPONENT_AT_AR_BARREL_01", Hash: "0x43A49D26" },
        { name: "Heavy Barrel", Hash_Key: "COMPONENT_AT_AR_BARREL_02", Hash: "0x5646C26A" },
        { name: "Digital Camo", Hash_Key: "COMPONENT_ASSAULTRIFLE_MK2_CAMO", Hash: "0x911B24AF" },
        { name: "Brushstroke Camo", Hash_Key: "COMPONENT_ASSAULTRIFLE_MK2_CAMO_02", Hash: "0x37E5444B" },
        { name: "Woodland Camo", Hash_Key: "COMPONENT_ASSAULTRIFLE_MK2_CAMO_03", Hash: "0x538B7B97" },
        { name: "Skull", Hash_Key: "COMPONENT_ASSAULTRIFLE_MK2_CAMO_04", Hash: "0x25789F72" },
        { name: "Sessanta Nove", Hash_Key: "COMPONENT_ASSAULTRIFLE_MK2_CAMO_05", Hash: "0xC5495F2D" },
        { name: "Perseus", Hash_Key: "COMPONENT_ASSAULTRIFLE_MK2_CAMO_06", Hash: "0xCF8B73B1" },
        { name: "Leopard", Hash_Key: "COMPONENT_ASSAULTRIFLE_MK2_CAM O_07", Hash: "0xA9BB2811" },
        { name: "Zebra", Hash_Key: "COMPONENT_ASSAULTRIFLE_MK2_CAMO_08", Hash: "0xFC674D54" },
        { name: "Geometric", Hash_Key: "COMPONENT_ASSAULTRIFLE_MK2_CAMO_09", Hash: "0x7C7FCD9B" },
        { name: "Boom!", Hash_Key: "COMPONENT_ASSAULTRIFLE_MK2_CAMO_10", Hash: "0xA5C38392" },
        { name: "Patriotic", Hash_Key: "COMPONENT_ASSAULTRIFLE_MK2_CAMO_IND_01", Hash: "0xB9B15DB0" },
    ]},
    {name: "Compact Rifle", type: FiveVWeaponType.RIFLE, Hash: "WEAPON_COMPACTRIFLE", Model_Hash_Key: "w_ar_assaultrifle_smg", DLC: GTADLC.MPLOWRIDER2, Description: "Half the size, all the power, double the recoil: there's no riskier way to say \"I'm compensating for something\". Part of Lowriders: Custom Classics.",
    Components: [// Compact Rifle
        { name: "Default Clip", Hash_Key: "COMPONENT_COMPACTRIFLE_CLIP_01", Hash: "0x513F0A63" },
        { name: "Extended Clip", Hash_Key: "COMPONENT_COMPACTRIFLE_CLIP_02", Hash: "0x59FF9BF8" },
        { name: "Drum Magazine", Hash_Key: "COMPONENT_COMPACTRIFLE_CLIP_03", Hash: "0xC607740E" },
    ]},
    {name: "Battle Rifle", type: FiveVWeaponType.RIFLE, Hash: "WEAPON_BATTLERIFLE", Model_Hash_Key: "W_SL_BattleRifle_M32", DLC: GTADLC.MP2023} // To be done
]

export const FiveVWeaponComponents : FiveVWeaponComponent[] = [

    // Switchblade
    { name: "Default Handle", Hash_Key: "COMPONENT_SWITCHBLADE_VARMOD_BASE", Hash: "0x9137A500" },
    { name: "VIP Variant", Hash_Key: "COMPONENT_SWITCHBLADE_VARMOD_VAR1", Hash: "0x5B3E7DB6" },
    { name: "Bodyguard Variant", Hash_Key: "COMPONENT_SWITCHBLADE_VARMOD_VAR2", Hash: "0xE7939662" },

    // Pistols
    { name: "Default Clip", Hash_Key: "COMPONENT_PISTOL_CLIP_01", Hash: "0xFED0FD71" },
    { name: "Extended Clip", Hash_Key: "COMPONENT_PISTOL_CLIP_02", Hash: "0xED265A1C" },
    { name: "Flashlight", Hash_Key: "COMPONENT_AT_PI_FLSH", Hash: "0x359B7AAE" },
    { name: "Suppressor", Hash_Key: "COMPONENT_AT_PI_SUPP_02", Hash: "0x65EA7EBB" },
    { name: "Yusuf Amir Luxury Finish", Hash_Key: "COMPONENT_PISTOL_VARMOD_LUXE", Hash: "0xD7391086" },

    // Combat Pistol
    { name: "Default Clip", Hash_Key: "COMPONENT_COMBATPISTOL_CLIP_01", Hash: "0x721B079" },
    { name: "Extended Clip", Hash_Key: "COMPONENT_COMBATPISTOL_CLIP_02", Hash: "0xD67B4F2D" },
    { name: "Flashlight", Hash_Key: "COMPONENT_AT_PI_FLSH", Hash: "0x359B7AAE" },
    { name: "Suppressor", Hash_Key: "COMPONENT_AT_PI_SUPP", Hash: "0xC304849A" },
    { name: "Yusuf Amir Luxury Finish", Hash_Key: "COMPONENT_COMBATPISTOL_VARMOD_LOWRIDER", Hash: "0xC6654D72" },

    // AP Pistol
    { name: "Default Clip", Hash_Key: "COMPONENT_APPISTOL_CLIP_01", Hash: "0x31C4B22A" },
    { name: "Extended Clip", Hash_Key: "COMPONENT_APPISTOL_CLIP_02", Hash: "0x249A17D5" },
    { name: "Flashlight", Hash_Key: "COMPONENT_AT_PI_FLSH", Hash: "0x359B7AAE" },
    { name: "Suppressor", Hash_Key: "COMPONENT_AT _PI_SUPP", Hash: "0xC304849A" },
    { name: "Gilded Gun Metal Finish", Hash_Key: "COMPONENT_APPISTOL_VARMOD_LUXE", Hash: "0x9B76C72C" },

    // Pistol .50
    { name: "Default Clip", Hash_Key: "COMPONENT_PISTOL50_CLIP_01", Hash: "0x2297BE19" },
    { name: "Extended Clip", Hash_Key: "COMPONENT_PISTOL50_CLIP_02", Hash: "0xD9D3AC92" },
    { name: "Flashlight", Hash_Key: "COMPONENT_AT_PI_FLSH", Hash: "0x359B7AAE" },
    { name: "Suppressor", Hash_Key: "COMPONENT_AT_AR_SUPP_02", Hash: "0xA73D4664" },
    { name: "Platinum Pearl Deluxe Finish", Hash_Key: "COMPONENT_PISTOL50_VARMOD_LUXE", Hash: "0x77B8AB2F" },

    // Heavy Revolver
    { name: "VIP Variant", Hash_Key: "COMPONENT_REVOLVER_VARMOD_BOSS", Hash: "0x16EE3040" },
    { name: "Bodyguard Variant", Hash_Key: "COMPONENT_REVOLVER_VARMOD_GOON", Hash: "0x9493B80D" },
    { name: "Default Clip", Hash_Key: "COMPONENT_REVOLVER_CLIP_01", Hash: "0xE9867CE3" },

    // SNS Pistol
    { name: "Default Clip", Hash_Key: "COMPONENT_SNSPISTOL_CLIP_01", Hash: "0xF8802ED9" },
    { name: "Extended Clip", Hash_Key: "COMPONENT_SNSPISTOL_CLIP_02", Hash: "0x7B0033B3" },
    { name: "Etched Wood Grip Finish", Hash_Key: "COMPONENT_SNSPISTOL_VARMOD_LOWRIDER", Hash: "0x8033ECAF" },

    // Heavy Pistol
    { name: "Default Clip", Hash_Key: "COMPONENT_HEAVYPISTOL_CLIP_01", Hash: "0xD4A969A" },
    { name: "Extended Clip", Hash_Key: "COMPONENT_HEAVYPISTOL_CLIP_02", Hash: "0x64F9C62B" },
    { name: "Flashlight", Hash_Key: "COMPONENT_AT_PI_FLSH", Hash: "0x359B7AAE" },
    { name: "Suppressor", Hash_Key: "COMPONENT_AT_PI_SUPP", Hash: "0xC304849A" },
    { name: "Etched Wood Grip Finish", Hash_Key: "COMPONENT_HEAVYPISTOL_VARMOD_LUXE", Hash: "0x7A6A7B7B" },

    // Heavy Revolver Mk II
    { name: "Default Rounds", Hash_Key: "COMPONENT_REVOLVER_MK2_CLIP_01", Hash: "0xBA23D8BE" },
    { name: "Tracer Rounds", Hash_Key: "COMPONENT_REVOLVER_MK2_CLIP_TRACER", Hash: "0xC6D8E476" },
    { name: "Incendiary Rounds", Hash_Key: "COMPONENT_REVOLVER_MK2_CLIP_INCENDIARY", Hash: "0xEFBF25" },
    { name: "Hollow Point Rounds", Hash_Key: "COMPONENT_REVOLVER_MK2_CLIP_HOLLOWPOINT", Hash: "0x10F42E8F" },
    { name: "Full Metal Jacket Rounds", Hash_Key: "COMPONENT_REVOLVER_MK2_CLIP_FMJ", Hash: "0xDC8BA3F" },
    { name: "Holographic Sight", Hash_Key: "COMPONENT_AT_SIGHTS", Hash: "0x420FD713" },
    { name: "Small Scope", Hash_Key: "COMPONENT_AT_SCOPE_MACRO_MK2", Hash: "0x49B2945" },
    { name: "Flashlight", Hash_Key: "COMPONENT_AT_PI_FLSH", Hash: "0x359B7AAE" },
    { name: "Compensator", Hash_Key: "COMPONENT_AT_PI_COMP_03", Hash: "0x27077CCB" },
    { name: "Digital Camo", Hash_Key: "COMPONENT_REVOLVER_MK2_CAMO", Hash: "0xC03FED9F" },
    { name: "Brushstroke Camo", Hash_Key: "COMPONENT_REVOLVER_MK2_CAMO_02", Hash: "0xB5DE24" },
    { name: "Woodland Camo", Hash_Key: "COMPONENT_REVOLVER_MK2_CAMO_03", Hash: "0xA7FF1B8" },
    { name: "Skull", Hash_Key: "COMPONENT_REVOLVER_MK2_CAMO_04", Hash: "0xF2E24289" },
    { name: "Sessanta Nove", Hash_Key: "COMPONENT_REVOLVER_MK2_CAMO_05", Hash: "0x11317F27" },
    { name: "Perseus", Hash_Key: "COMPONENT_REVOLVER_MK2_CAMO_06", Hash: "0x17C30C42" },
    { name: "Leopard", Hash_Key: "COMPONENT_REVOLVER_MK2_CAMO_07", Hash: "0x257927AE" },
    { name: "Zebra", Hash_Key: "COMPONENT_REVOLVER_MK2_CAMO_08", Hash: "0x37304B1C" },
    { name: "Geometric", Hash_Key: "COMPONENT_REVOLVER_MK2_CAMO_09", Hash: "0x48DAEE71" },
    { name: "Boom!", Hash_Key: "COMPONENT_REVOLVER_MK2_CAMO_10", Hash: "0x20ED9B5B" },
    { name: "Patriotic", Hash_Key: "COMPONENT_REVOLVER_MK2_CAMO_IND_01", Hash: "0xD951E867" },

    // SNS Pistol Mk II
    { name: "Default Clip", Hash_Key: "COMPONENT_SNSPISTOL_MK2_CLIP_01", Hash: "0x1466CE6" },
    { name: "Extended Clip", Hash_Key: "COMPONENT_SNSPISTOL_MK2_CLIP_02", Hash: "0xCE8C0772" },
    { name: "Tracer Rounds", Hash_Key: "COMPONENT_SNSPISTOL_MK2_CLIP_TRACER", Hash: "0x902DA26E" },
    { name: "Incendiary Rounds", Hash_Key: "COMPONENT_SNSPISTOL_MK2_CLIP_INCENDIARY", Hash: "0xE6AD5F79" },
    { name: "Hollow Point Rounds", Hash_Key: "COMPONENT_SNSPISTOL_MK2_CLIP_HOLLOWPOINT", Hash: "0x8D107402" },
    { name: "Full Metal Jacket Rounds", Hash_Key: "COMPONENT_SNSPISTOL_MK2_CLIP_FMJ", Hash: "0xC111EB26" },
    { name: "Flashlight", Hash_Key: "COMPONENT_AT_PI_FLSH_03", Hash: "0x4A4965F3" },
    { name: "Mounted Scope", Hash_Key: "COMPONENT_AT_PI_RAIL_02", Hash: "0x47DE9258" },
    { name: "Suppressor", Hash_Key: "COMPONENT_AT_PI_SUPP_02", Hash: "0x65EA7EBB" },
    { name: "Compensator", Hash_Key: "COMPONENT_AT_PI_COMP_02", Hash: "0xAA8283BF" },
    { name: "Digital Camo", Hash_Key: "COMPONENT_SNSPISTOL_MK2_CAMO", Hash: "0xF7BEEDD" },
    { name: "Brushstroke Camo", Hash_Key: "COMPONENT_SNSPISTOL_MK2_CAMO_02", Hash: "0x8A612EF6" },
    { name: "Woodland Camo", Hash_Key: "COMPONENT_SNSPISTOL_MK2_CAMO_03", Hash: "0x76FA8829" },
    { name: "Skull", Hash_Key: "COMPONENT_SNSPISTOL_MK2_CAMO_04", Hash: "0xA93C6CAC" },
    { name: "Sessanta Nove", Hash_Key: "COMPONENT_SNSPISTOL_MK2_CAMO_05", Hash: "0x9C905354" },
    { name: "Perseus", Hash_Key: "COMPONENT_SNSPISTOL_MK2_CAMO_06", Hash: "0x4DFA3621" },
    { name: "Leopard", Hash_Key: "COMPONENT_SNSPISTOL_MK2_CAMO_07", Hash: "0x42E91FFF" },
    { name: "Zebra", Hash_Key: "COMPONENT_SNSPISTOL_MK2_CAMO_08", Hash: "0x54A8437D" },
    { name: "Geometric", Hash_Key: "COMPONENT_SNSPISTOL_MK2_CAMO_09", Hash: "0x68C2746" },
    { name: "Boom!", Hash_Key: "COMPONENT_SNSPISTOL_MK2_CAMO_10", Hash: "0x2366E467" },
    { name: "Patriotic", Hash_Key: "COMPONENT_SNSPISTOL_MK2_CAMO_IND_01", Hash: "0x441882E6" },
    { name: "Digital Camo", Hash_Key: "COMPONENT_SNSPISTOL_MK2_CAMO_SLIDE", Hash: "0xE7EE68EA" },
    { name: "Brushstroke Camo", Hash_Key: "COMPONENT_SNSPISTOL_MK2_CAMO_02_SLIDE", Hash: "0x29366D21" },
    { name: "Woodland Camo", Hash_Key: "COMPONENT_SNSPISTOL_MK2_CAMO_03_SLIDE", Hash: "0x3ADE514B" },
    { name: "Skull", Hash_Key: "COMPONENT_SNSPISTOL_MK2_CAMO_04_SLIDE", Hash: "0xE64513E 9" },
    { name: "Sessanta Nove", Hash_Key: "COMPONENT_SNSPISTOL_MK2_CAMO_05_SLIDE", Hash: "0xCD7AEB9A" },
    { name: "Perseus", Hash_Key: "COMPONENT_SNSPISTOL_MK2_CAMO_06_SLIDE", Hash: "0xFA7B27A6" },
    { name: "Leopard", Hash_Key: "COMPONENT_SNSPISTOL_MK2_CAMO_07_SLIDE", Hash: "0xE285CA9A" },
    { name: "Zebra", Hash_Key: "COMPONENT_SNSPISTOL_MK2_CAMO_08_SLIDE", Hash: "0x2B904B19" },
    { name: "Geometric", Hash_Key: "COMPONENT_SNSPISTOL_MK2_CAMO_09_SLIDE", Hash: "0x22C24F9C" },
    { name: "Boom!", Hash_Key: "COMPONENT_SNSPISTOL_MK2_CAMO_10_SLIDE", Hash: "0x8D0D5ECD" },
    { name: "Patriotic", Hash_Key: "COMPONENT_SNSPISTOL_MK2_CAMO_IND_01_SLIDE", Hash: "0x1F07150A" },

    // Pistol Mk II
    { name: "Default Clip", Hash_Key: "COMPONENT_PISTOL_MK2_CLIP_01", Hash: "0x94F42D62" },
    { name: "Extended Clip", Hash_Key: "COMPONENT_PISTOL_MK2_CLIP_02", Hash: "0x5ED6C128" },
    { name: "Tracer Rounds", Hash_Key: "COMPONENT_PISTOL_MK2_CLIP_TRACER", Hash: "0x25CAAEAF" },
    { name: "Incendiary Rounds", Hash_Key: "COMPONENT_PISTOL_MK2_CLIP_INCENDIARY", Hash: "0x2BBD7A3A" },
    { name: "Hollow Point Rounds", Hash_Key: "COMPONENT_PISTOL_MK2_CLIP_HOLLOWPOINT", Hash: "0x85FEA109" },
    { name: "Full Metal Jacket Rounds", Hash_Key: "COMPONENT_PISTOL_MK2_CLIP_FMJ", Hash: "0x4F37DF2A" },
    { name: "Mounted Scope", Hash_Key: "COMPONENT_AT_PI_RAIL", Hash: "0x8ED4BB70" },
    { name: "Flashlight", Hash_Key: "COMPONENT_AT_PI_FLSH_02", Hash: "0x43FD595B" },
    { name: "Suppressor", Hash_Key: "COMPONENT_AT_PI_SUPP_02", Hash: "0x65EA7EBB" },
    { name: "Compensator", Hash_Key: "COMPONENT_AT_PI_COMP", Hash: "0x21E34793" },
    { name: "Digital Camo", Hash_Key: "COMPONENT_PISTOL_MK2_CAMO", Hash: "0x5C6C749C" },
    { name: "Brushstroke Camo", Hash_Key: "COMPONENT_PISTOL_MK2_CAMO_02", Hash: "0x15F7A390" },
    { name: "Woodland Camo", Hash_Key: "COMPONENT_PISTOL_MK2_CAMO_03", Hash: "0x968E24DB" },
    { name: "Skull", Hash_Key: "COMPONENT_PISTOL_MK2_CAMO_04", Hash: "0x17BFA99" },
    { name: "Sessanta Nove", Hash_Key: "COMPONENT_PISTOL_MK2_CAMO_05", Hash: "0xF2685C72" },
    { name: "Perseus", Hash_Key: "COMPONENT_PISTOL_MK2_CAMO_06", Hash: "0xDD2231E6" },
    { name: "Leopard", Hash_Key: "COMPONENT_PISTOL_MK2_CAMO_07", Hash: "0xBB43EE76" },
    { name: "Zebra", Hash_Key: "COMPONENT_PISTOL_MK2_CAMO_08", Hash: "0x4D901310" },
    { name: "Geometric", Hash_Key: "COMPONENT_PISTOL_MK2_CAMO_09", Hash: "0x5F31B653" },
    { name: "Boom!", Hash_Key: "COMPONENT_PISTOL_MK2_CAMO_10", Hash: "0x697E19A0" },
    { name: "Patriotic", Hash_Key: "COMPONENT_PISTOL_MK2_CAMO_IND_01", Hash: "0x930CB951" },
    { name: "Digital Camo", Hash_Key: "COMPONENT_PISTOL_MK2_CAMO_SLIDE", Hash: "0xB4FC92B0" },
    { name: "Brushstroke Camo", Hash_Key: "COMPONENT_PISTOL_MK2_CAMO_02_SLIDE", Hash: "0x1A1F1260" },
    { name: "Woodland Camo", Hash_Key: "COMPONENT_PISTOL_MK2_CAMO_03_SLIDE", Hash: "0xE4E00B70" },
    { name: "Skull", Hash_Key: "COMPONENT_PISTOL_MK2_CAMO_04_SLIDE", Hash: "0x2C298B2B" },
    { name: "Sessanta Nove", Hash_Key: "COMPONENT_PISTOL_MK2_CAMO_05_SLIDE", Hash: "0x DFB79725" },
    { name: "Perseus", Hash_Key: "COMPONENT_PISTOL_MK2_CAMO_06_SLIDE", Hash: "0x6BD7228C" },
    { name: "Leopard", Hash_Key: "COMPONENT_PISTOL_MK2_CAMO_07_SLIDE", Hash: "0x9DDBCF8C" },
    { name: "Zebra", Hash_Key: "COMPONENT_PISTOL_MK2_CAMO_08_SLIDE", Hash: "0xB319A52C" },
    { name: "Geometric", Hash_Key: "COMPONENT_PISTOL_MK2_CAMO_09_SLIDE", Hash: "0xC6836E12" },
    { name: "Boom!", Hash_Key: "COMPONENT_PISTOL_MK2_CAMO_10_SLIDE", Hash: "0x43B1B173" },
    { name: "Patriotic", Hash_Key: "COMPONENT_PISTOL_MK2_CAMO_IND_01_SLIDE", Hash: "0x4ABDA3FA" },

    // Vintage Pistol
    { name: "Default Clip", Hash_Key: "COMPONENT_VINTAGEPISTOL_CLIP_01", Hash: "0x45A3B6BB" },
    { name: "Extended Clip", Hash_Key: "COMPONENT_VINTAGEPISTOL_CLIP_02", Hash: "0x33BA12E8" },
    { name: "Suppressor", Hash_Key: "COMPONENT_AT_PI_SUPP", Hash: "0xC304849A" },

    // Up-n-Atomizer
    { name: "Festive tint", Hash_Key: "COMPONENT_RAYPISTOL_VARMOD_XMAS18", Hash: "0xD7DBF707" },

    // Ceramic Pistol
    { name: "Default Clip", Hash_Key: "COMPONENT_CERAMICPISTOL_CLIP_01", Hash: "0x54D41361" },
    { name: "Extended Clip", Hash_Key: "COMPONENT_CERAMICPISTOL_CLIP_02", Hash: "0x81786CA9" },
    { name: "Suppressor", Hash_Key: "COMPONENT_CERAMICPISTOL_SUPP", Hash: "0x9307D6FA" },

    // Micro SMG
    { name: "Default Clip", Hash_Key: "COMPONENT_MICROSMG_CLIP_01", Hash: "0xCB48AEF0" },
    { name: "Extended Clip", Hash_Key: "COMPONENT_MICROSMG_CLIP_02", Hash: "0x10E6BA2B" },
    { name: "Flashlight", Hash_Key: "COMPONENT_AT_PI_FLSH", Hash: "0x359B7AAE" },
    { name: "Scope", Hash_Key: "COMPONENT_AT_SCOPE_MACRO", Hash: "0x9D2FBF29" },
    { name: "Suppressor", Hash_Key: "COMPONENT_AT_AR_SUPP_02", Hash: "0xA73D4664" },
    { name: "Yusuf Amir Luxury Finish", Hash_Key: "COMPONENT_MICROSMG_VARMOD_LUXE", Hash: "0x487AAE09" },

    // SMG
    { name: "Default Clip", Hash_Key: "COMPONENT_SMG_CLIP_01", Hash: "0x26574997" },
    { name: "Extended Clip", Hash_Key: "COMPONENT_SMG_CLIP_02", Hash: "0x350966FB" },
    { name: "Drum Magazine", Hash_Key: "COMPONENT_SMG_CLIP_03", Hash: "0x79C77076" },
    { name: "Flashlight", Hash_Key: "COMPONENT_AT_AR_FLSH", Hash: "0x7BC4CDDC" },
    { name: "Scope", Hash_Key: "COMPONENT_AT_SCOPE_MACRO_02", Hash: "0x3CC6BA57" },
    { name: "Suppressor", Hash_Key: "COMPONENT_AT_PI_SUPP", Hash: "0xC304849A" },
    { name: "Yusuf Amir Luxury Finish", Hash_Key: "COMPONENT_SMG_VARMOD_LUXE", Hash: "0x27872C90" },

    // Assault SMG
    { name: "Default Clip", Hash_Key: "COMPONENT_ASSAULTSMG_CLIP_01", Hash: "0x8D1307B0" },
    { name: "Extended Clip", Hash_Key: "COMPONENT_ASSAULTSMG_CLIP_02", Hash: "0xBB46E417" },
    { name: "Flashlight", Hash_Key: "COMPONENT_AT_AR_FLSH", Hash: "0x7BC4CDDC" },
    { name: "Scope", Hash_Key: "COMPONENT_AT_SCOPE_MACRO", Hash: "0x9D2FBF29" },
    { name: "Suppressor", Hash_Key: "COMPONENT_AT_AR_SUPP_02", Hash: "0xA73D4664" },
    { name: "Yusuf Amir Luxury Finish", Hash_Key: "COMPONENT_ASSAULTSMG_VARMOD_LOWRIDER", Hash: "0x278C78AF" },

    // Mini SMG
    { name: "Default Clip", Hash_Key: "COMPONENT_MINISMG_CLIP_01", Hash: "0x84C8B2D3" },
    { name: "Extended Clip", Hash_Key: "COMPONENT_MINISMG_CLIP_02", Hash: "0x937ED0B7" },

    // SMG Mk II
    { name: "Default Clip", Hash_Key: "COMPONENT_SMG_MK2_CLIP_01", Hash: "0x4C24806E" },
    { name: "Extended Clip", Hash_Key: "COMPONENT_SMG_MK2_CLIP_02", Hash: "0xB9835B2E" },
    { name: "Tracer Rounds", Hash_Key: "COMPONENT_SMG_MK2_CLIP_TRACER", Hash: "0x7FEA36EC" },
    { name: "Incendiary Rounds", Hash_Key: "COMPONENT_SMG_MK2_CLIP_INCENDIARY", Hash: "0xD99222E5" },
    { name: "Hollow Point Rounds", Hash_Key: "COMPONENT_SMG_MK2_CLIP_HOLLOWPOINT", Hash: "0x3A1BD6FA" },
    { name: "Full Metal Jacket Rounds", Hash_Key: "COMPONENT_SMG_MK2_CLIP_FMJ", Hash: "0xB5A715F" },
    { name: "Flashlight", Hash_Key: "COMPONENT_AT_AR_FLSH", Hash: "0x7BC4CDDC" },
    { name: "Holographic Sight", Hash_Key: "COMPONENT_AT_SIGHTS_SMG", Hash: "0x9FDB5652" },
    { name: "Small Scope", Hash_Key: "COMPONENT_AT_SCOPE_MACRO_02_SMG_MK2", Hash: "0xE502AB6B" },
    { name: "Medium Scope", Hash_Key: "COMPONENT_AT_SCOPE_SMALL_SMG_MK2", Hash: "0x3DECC7DA" },
    { name: "Suppressor", Hash_Key: "COMPONENT_AT_PI_SUPP", Hash: "0xC304849A" },
    { name: "Flat Muzzle Brake", Hash_Key: "COMPONENT_AT_MUZZLE_01", Hash: "0xB99402D4" },
    { name: "Tactical Muzzle Brake", Hash_Key: "COMPONENT_AT_MUZZLE_02", Hash: "0xC867A07B" },
    { name: "Fat-End Muzzle Brake", Hash_Key: "COMPONENT_AT_MUZZLE_03", Hash: "0xDE11CBCF" },
    { name: "Precision Muzzle Brake", Hash_Key: "COMPONENT_AT_MUZZLE_04", Hash: "0xEC9068CC" },
    { name: "Heavy Duty Muzzle Brake", Hash_Key: "COMPONENT_AT_MUZZLE_05", Hash: "0x2E7957A" },
    { name: "Slanted Muzzle Brake", Hash_Key: "COMPONENT_AT_MUZZLE_06", Hash: "0x347EF8AC" },
    { name: "Split-End Muzzle Brake", Hash_Key: "COMPONENT_AT_MUZZLE_07", Hash: "0x4DB62ABE" },
    { name: "Default Barrel", Hash_Key: "COMPONENT_AT_SB_BARREL_01", Hash: "0xD9103EE1" },
    { name: "Heavy Barrel", Hash_Key: "COMPONENT_AT_SB_BARREL_02", Hash: "0xA564D78B" },
    { name: "Digital Camo", Hash_Key: "COMPONENT_SMG_MK2_CAMO", Hash: "0xC4979067" },
    { name: "Brushstroke Camo", Hash_Key: "COMPONENT_SMG_MK2_CAMO_02", Hash: "0x3815A945" },
    { name: "Woodland Camo", Hash_Key: "COMPONENT_SMG_MK2_CAMO_03", Hash: "0x4B4B4FB0" },
    { name: "Skull", Hash_Key: "COMPONENT_SMG_MK2_CAMO_04", Hash: "0xEC729200" },
    { name: "Sessanta Nove", Hash_Key: "COMPONENT_SMG_MK2_CAMO_05", Hash: "0x48F64B22" },
    { name: "Perseus", Hash_Key: "COMPONENT_SMG_MK2_CAMO_06", Hash: "0x35992468" },
    { name: "Leopard", Hash_Key: "COMPONENT_SMG_MK2_CAMO_07", Hash: "0x24B782A 5" },
    { name: "Zebra", Hash_Key: "COMPONENT_SMG_MK2_CAMO_08", Hash: "0xA2E67F01" },
    { name: "Geometric", Hash_Key: "COMPONENT_SMG_MK2_CAMO_09", Hash: "0x2218FD68" },
    { name: "Boom!", Hash_Key: "COMPONENT_SMG_MK2_CAMO_10", Hash: "0x45C5C3C5" },
    { name: "Patriotic", Hash_Key: "COMPONENT_SMG_MK2_CAMO_IND_01", Hash: "0x399D558F" },

    // Machine Pistol
    { name: "Default Clip", Hash_Key: "COMPONENT_MACHINEPISTOL_CLIP_01", Hash: "0x476E85FF" },
    { name: "Extended Clip", Hash_Key: "COMPONENT_MACHINEPISTOL_CLIP_02", Hash: "0xB92C6979" },
    { name: "Drum Magazine", Hash_Key: "COMPONENT_MACHINEPISTOL_CLIP_03", Hash: "0xA9E9CAF4" },
    { name: "Suppressor", Hash_Key: "COMPONENT_AT_PI_SUPP", Hash: "0xC304849A" },

    // Combat PDW
    { name: "Default Clip", Hash_Key: "COMPONENT_COMBATPDW_CLIP_01", Hash: "0x4317F19E" },
    { name: "Extended Clip", Hash_Key: "COMPONENT_COMBATPDW_CLIP_02", Hash: "0x334A5203" },
    { name: "Drum Magazine", Hash_Key: "COMPONENT_COMBATPDW_CLIP_03", Hash: "0x6EB8C8DB" },
    { name: "Flashlight", Hash_Key: "COMPONENT_AT_AR_FLSH", Hash: "0x7BC4CDDC" },
    { name: "Grip", Hash_Key: "COMPONENT_AT_AR_AFGRIP", Hash: "0xC164F53" },
    { name: "Scope", Hash_Key: "COMPONENT_AT_SCOPE_SMALL", Hash: "0xAA2C45B4" },

    // Pump Shotgun
    { name: "Flashlight", Hash_Key: "COMPONENT_AT_AR_FLSH", Hash: "0x7BC4CDDC" },
    { name: "Suppressor", Hash_Key: "COMPONENT_AT_SR_SUPP", Hash: "0xE608B35E" },
    { name: "Yusuf Amir Luxury Finish", Hash_Key: "COMPONENT_PUMPSHOTGUN_VARMOD_LOWRIDER", Hash: "0xA2D79DDB" },

    // Sawed-Off Shotgun
    { name: "Gilded Gun Metal Finish", Hash_Key: "COMPONENT_SAWNOFFSHOTGUN_VARMOD_LUXE", Hash: "0x85A64DF9" },

    // Assault Shotgun
    { name: "Default Clip", Hash_Key: "COMPONENT_ASSAULTSHOTGUN_CLIP_01", Hash: "0x94E81BC7" },
    { name: "Extended Clip", Hash_Key: "COMPONENT_ASSAULTSHOTGUN_CLIP_02", Hash: "0x86BD7F72" },
    { name: "Flashlight", Hash_Key: "COMPONENT_AT_AR_FLSH", Hash: "0x7BC4CDDC" },
    { name: "Suppressor", Hash_Key: "COMPONENT_AT_AR_SUPP", Hash: "0x837445AA" },
    { name: "Grip", Hash_Key: "COMPONENT_AT_AR_AFGRIP", Hash: "0xC164F53" },

    // Bullpup Shotgun
    { name: "Flashlight", Hash_Key: "COMPONENT_AT_AR_FLSH", Hash: "0x7BC4CDDC" },
    { name: "Suppressor", Hash_Key: "COMPONENT_AT_AR_SUPP_02", Hash: "0xA73D4664" },
    { name: "Grip", Hash_Key: "COMPONENT_AT_AR_AFGRIP", Hash: "0xC164F53" },

    // Pump Shotgun Mk II
    { name: "Default Shells", Hash_Key: "COMPONENT_PUMPSHOTGUN_MK2_CLIP_01", Hash: "0xCD940141" },
    { name: "Dragon's Breath Shells", Hash_Key: "COMPONENT_PUMPSHOTGUN_MK2_CLIP_INCENDIARY", Hash: "0x9F8A1BF5" },
    { name: "Steel Buckshot Shells", Hash_Key: "COMPONENT_PUMPSHOTGUN_MK2_CLIP_ARMORPIERCING", Hash: "0x4E65B425" },
    { name: "Flechette Shells", Hash_Key: "COMPONENT_PUMPSHOTGUN_MK2_CLIP_HOLLOWPOINT", Hash: "0xE9582927" },
    { name: "Explosive Slugs", Hash_Key: "COMPONENT_PUMPSHOTGUN_MK2_CLIP_EXPLOSIVE", Hash: "0x3BE4465D" },
    { name: "Holographic Sight", Hash_Key: "COMPONENT_AT_SIGHTS", Hash: "0x420FD713" },
    { name: "Small Scope", Hash_Key: "COMPONENT_AT_SCOPE_MACRO_MK2", Hash: "0x49B2945" },
    { name: "Medium Scope", Hash_Key: "COMPONENT_AT_SCOPE_SMALL_MK2", Hash: "0x3F3C8181" },
    { name: "Flashlight", Hash_Key: "COMPONENT_AT_AR_FLSH", Hash: "0x7BC4CDDC" },
    { name: "Suppressor", Hash_Key: "COMPONENT_AT_SR_SUPP_03", Hash: "0xAC42DF71" },
    { name: "Squared Muzzle Brake", Hash_Key: "COMPONENT_AT_MUZZLE_08", Hash: "0x5F7DCE4D" },
    { name: "Digital Camo", Hash_Key: "COMPONENT_PUMPSHOTGUN_MK2_CAMO", Hash: "0xE3BD9E44" },
    { name: "Brushstroke Camo", Hash_Key: "COMPONENT_PUMPSHOTGUN_MK2_CAMO_02", Hash: "0x17148F9B" },
    { name: "Woodland Camo", Hash_Key: "COMPONENT_PUMPSHOTGUN_MK2_CAMO_03", Hash: "0x24D22B16" },
    { name: "Skull", Hash_Key: "COMPONENT_PUMPSHOTGUN_MK2_CAMO_04", Hash: "0xF2BEC6F0" },
    { name: "Sessanta Nove", Hash_Key: "COMPONENT_PUMPSHOTGUN_MK2_CAMO_05", Hash: "0x85627D" },
    { name: "Perseus", Hash_Key: "COMPONENT_PUMPSHOTGUN_MK2_CAMO_06", Hash: "0xDC2919C5" },
    { name: "Leopard", Hash_Key: "COMPONENT_PUMPSHOTGUN_MK2_CAMO_07", Hash: "0xE184247B" },
    { name: "Zebra", Hash_Key: "COMPONENT_PUMPSHOTGUN_MK2_CAMO_08", Hash: "0xD8EF9356" },
    { name: "Geometric", Hash_Key: "COMPONENT_PUMPSHOTGUN_MK2_CAMO_09", Hash: "0xEF29BFCA" },
    { name: "Boom!", Hash_Key: "COMPONENT_PUMPSHOTGUN_MK2_CAMO_10", Hash: "0x67AEB165" },
    { name: "Patriotic", Hash_Key: "COMPONENT_PUMPSHOTGUN_MK2_CAMO_IND_01", Hash: "0x46411A1D" },

    // Heavy Shotgun
    { name: "Default Clip", Hash_Key: "COMPONENT_HEAVYSHOTGUN_CLIP_01", Hash: "0x324F2D5F" },
    { name: "Extended Clip", Hash_Key: "COMPONENT_HEAVYSHOTGUN_CLIP_02", Hash: "0x971CF6FD" },
    { name: "Drum Magazine", Hash_Key: "COMPONENT_HEAVYSHOTGUN_CLIP_03", Hash: "0x88C7DA53" },
    { name: "Flashlight", Hash_Key: "COMPONENT_AT_AR_FLSH", Hash: "0x7BC4CDDC" },
    { name: "Suppressor", Hash_Key: "COMPONENT_AT_AR_SUPP_02", Hash: "0xA73D4664" },
    { name: "Grip", Hash_Key: "COMPONENT_AT_AR_AFGRIP", Hash: "0xC164F53" },

    // Assault Rifle
    { name: "Default Clip", Hash_Key: "COMPONENT_ASSAULTRIFLE_CLIP_01", Hash: "0xBE5EEA16" },
    { name: "Extended Clip", Hash_Key: "COMPONENT_ASSAULTRIFLE_CLIP_02", Hash: "0xB1214F9B" },
    { name: "Drum Magazine", Hash_Key: "COMPONENT_ASSAULTRIFLE_CLIP_03", Hash: "0xDBF0A53D" },
    { name: "Flashlight", Hash_Key: "COMPONENT_AT_AR_FLSH", Hash: "0x7BC4CDDC" },
    { name: "Scope", Hash_Key: "COMPONENT_AT_SCOPE_MACRO", Hash: "0x9D2FBF29" },
    { name: "Suppressor", Hash_Key: "COMPONENT_AT_AR_SUPP_02", Hash: "0xA73D4664" },
    { name: "Grip", Hash_Key: "COMPONENT_AT_AR_AFGRIP", Hash: "0xC164F53" },
    { name: "Yusuf Amir Luxury Finish", Hash_Key: "COMPONENT_ASSAULTRIFLE_VARMOD_LUXE", Hash: "0x4EAD7533" },

    // Carbine Rifle
    { name: "Default Clip", Hash_Key: "COMPONENT_CARBINERIFLE_CLIP_01", Hash: "0x9FBE33EC" },
    { name: "Extended Clip", Hash_Key: "COMPONENT_CARBINERIFLE_CLIP_02", Hash: "0x91109691" },
    { name: "Box Magazine", Hash_Key: "COMPONENT_CARBINERIFLE_CLIP_03", Hash: "0xBA62E935" },
    { name: "Flashlight", Hash_Key: "COMPONENT_AT_AR_FLSH", Hash: "0x7BC4CDDC" },
    { name: "Scope", Hash_Key: "COMPONENT_AT_SCOPE_MEDIUM", Hash: "0xA0D89C42" },
    { name: "Suppressor", Hash_Key: "COMPONENT_AT_AR_SUPP", Hash: "0x837445AA" },
    { name: "Grip", Hash_Key: "COMPONENT_AT_AR_AFGRIP", Hash: "0xC164F53" },
    { name: "Yusuf Amir Luxury Finish", Hash_Key: "COMPONENT_CARBINERIFLE_VARMOD_LUXE", Hash: "0xD89B9658" },

    // Advanced Rifle
    { name: "Default Clip", Hash_Key: "COMPONENT_ADVANCEDRIFLE_CLIP_01", Hash: "0xFA8FA10F" },
    { name: "Extended Clip", Hash_Key: "COMPONENT_ADVANCEDRIFLE_CLIP_02", Hash: "0x8EC1C979" },
    { name: "Flashlight", Hash_Key: "COMPONENT_AT_AR_FLSH", Hash: "0x7BC4CDDC" },
    { name: "Scope", Hash_Key: "COMPONENT_AT_SCOPE_SMALL", Hash: "0xAA2C45B4" },
    { name: "Suppressor", Hash_Key: "COMPONENT_AT_AR_SUPP", Hash: "0x837445AA" },
    { name: "Yusuf Amir Luxury Finish", Hash_Key: "COMPONENT_ADVANCEDRIFLE_VARMOD_LUXE", Hash: "0x377CD377" },

    // Special Carbine
    { name: "Default Clip", Hash_Key: "COMPONENT_SPECIALCARBINE_CLIP_01", Hash: "0xC6C7E581" },
    { name: "Extended Clip", Hash_Key: "COMPONENT_SPECIALCARBINE_CLIP_02", Hash: "0x7C8BD10E" },
    { name: "Drum Magazine", Hash_Key: "COMPONENT_SPECIALCARBINE_CLIP_03", Hash: "0x6B59AEAA" },
    { name: "Flashlight", Hash_Key: "COMPONENT_AT_AR_FLSH", Hash: "0x7BC4CDDC" },
    { name: "Scope", Hash_Key: "COMPONENT_AT_SCOPE_MEDIUM", Hash: "0xA0D89C42" },
    { name: "Suppressor", Hash_Key: "COMPONENT_AT_AR_SUPP_02", Hash: "0xA73D4664" },
    { name: "Grip", Hash_Key: "COMPONENT_AT_AR_AFGRIP", Hash: "0xC164F53" },
    { name: "Etched Gun Metal Finish", Hash_Key: "COMPONENT_SPECIALCARBINE_VARMOD_LOWRIDER", Hash: "0x730154F2" },

    // Bullpup Rifle
    { name: "Default Clip", Hash_Key: "COMPONENT_BULLPUPRIFLE_CLIP_01", Hash: "0xC5A12F80" },
    { name: "Extended Clip", Hash_Key: "COMPONENT_BULLPUPRIFLE_CLIP_02", Hash: "0xB3688B0F" },
    { name: "Flashlight", Hash_Key: "COMPONENT_AT_AR_FLSH", Hash: "0x7BC4CDDC" },
    { name: "Scope", Hash_Key: "COMPONENT_AT_SCOPE_SMALL", Hash: "0xAA2C45B4" },
    { name: "Suppressor", Hash_Key: "COMPONENT_AT_AR_SUPP", Hash: "0x837445AA" },
    { name: "Grip", Hash_Key: "COMPONENT_AT_AR_AFGRIP", Hash: "0xC164F53" },
    { name: "Gilded Gun Metal Finish", Hash_Key: "COMPONENT_BULLPUPRIFLE_VARMOD_LOW", Hash: "0xA857BC78" },

    // Bullpup Rifle Mk II
    { name: "Default Clip", Hash_Key: "COMPONENT_BULLPUPRIFLE_MK2_CLIP_01", Hash: "0x18929DA" },
    { name: "Extended Clip", Hash_Key: "COMPONENT_BULLPUPRIFLE_MK2_CLIP_02", Hash: "0xEFB00628" },
    { name: "Tracer Rounds", Hash_Key: "COMPONENT_BULLPUPRIFLE_MK2_CLIP_TRACER", Hash: "0x822060A9" },
    { name: "Incendiary Rounds", Hash_Key: "COMPONENT_BULLPUPRIFLE_MK2_CLIP_INCENDIARY", Hash: "0xA99CF95A" },
    { name: "Armor Piercing Rounds", Hash_Key: "COMPONENT_BULLPUPRIFLE_MK2_CLIP_ARMORPIERCING", Hash: "0xFAA7F5ED" },
    { name: "Full Metal Jacket Rounds", Hash_Key: "COMPONENT_BULLPUPRIFLE_MK2_CLIP_FMJ", Hash: "0x43621710" },
    { name: "Flashlight", Hash_Key: "COMPONENT_AT_AR_FLSH", Hash: "0x7BC4CDDC" },
    { name: "Holographic Sight", Hash_Key: "COMPONENT_AT_SIGHTS", Hash: "0x420FD713" },
    { name: "Small Scope", Hash_Key: "COMPONENT_AT_SCOPE_MACRO_02_MK2", Hash: "0xC7ADD105" },
    { name: "Medium Scope", Hash_Key: "COMPONENT_AT_SCOPE_SMALL_MK2", Hash: "0x3F3C8181" },
    { name: "Default Barrel", Hash_Key: "COMPONENT_AT_BP_BARREL_01", Hash: "0x659AC11B" },
    { name: "Heavy Barrel", Hash_Key: "COMPONENT_AT_BP_BARREL_02", Hash: "0x3BF26DC7" },
    { name: "Suppressor", Hash_Key: "COMPONENT_AT_AR_SUPP", Hash: "0x837445AA" },
    { name: "Flat Muzzle Brake", Hash_Key: "COMPONENT_AT_MUZZLE_01", Hash: "0xB99402D4" },
    { name: "Tactical Muzzle Brake", Hash_Key: "COMPONENT_AT_MUZZLE_02", Hash: "0xC867A07B" },
    { name: "Fat-End Muzzle Brake", Hash_Key: "COMPONENT_AT_MUZZLE_03", Hash: "0xDE11CBCF" },
    { name: "Precision Muzzle Brake", Hash_Key: "COMPONENT_AT_MUZZLE_04", Hash: "0xEC9068CC" },
    { name: "Heavy Duty Muzzle Brake", Hash_Key: "COMPONENT_AT_MUZZLE_05", Hash: "0x2E7957A" },
    { name: "Slanted Muzzle Brake", Hash_Key: "COMPONENT_AT_MUZZLE_06", Hash: "0x347EF8AC" },
    { name: "Split-End Muzzle Brake", Hash_Key: "COMPONENT_AT_MUZZLE_07", Hash: "0x4DB62ABE" },
    { name: "Grip", Hash_Key: "COMPONENT_AT_AR_AFGRIP_02", Hash: "0x9D65907A" },
    { name: "Digital Camo", Hash_Key: "COMPONENT_BULLPUPRIFLE_MK2_CAMO", Hash: "0xAE4055B7" },
    { name: "Brushstroke Camo", Hash_Key: "COMPONENT_BULLPUPRIFLE_MK2_CAMO_02", Hash: "0xB905ED6B" },
    { name: "Woodland Camo", Hash_Key: "COMPONENT_BULLPUPRIFLE_MK2_CAMO_03", Hash: "0xA6C448E8" },
    { name: "Skull", Hash_Key: "COMPONENT_BULLPUPRIFLE_MK2_CAMO_04", Hash: "0x9486246C" },
    { name: "Sessanta Nove", Hash_Key: "COMPONENT_BULLPUPRIFLE_MK2_CAMO_05", Hash: "0x8A390FD2" },
    { name: "Perseus", Hash_Key: "COMPONENT_BULLPUPRIFLE_MK2_CAMO_06", Hash: "0x2337FC5" },
    { name: "Leopard", Hash_Key: "COMPONENT_BULLPUPRIFLE_MK2_CAMO_07", Hash: "0xEFFFDB5E" },
    { name: "Zebra", Hash_Key: "COMPONENT_BULLPUPRIFLE_MK2_CAMO_08", Hash: "0xDDBDB6DA" },
    { name: "Geometric", Hash_Key: "COMPONENT_BULLPUPRIFLE_MK2_CAMO_09", Hash: "0xCB631225" },
    { name: "Boom!", Hash_Key: "COMPONENT_BULLPUPRIFLE_MK2_CAMO_10", Hash: "0xA87D541E" },
    { name: "Patriotic", Hash_Key: "COMPONENT_BULLPUPRIFLE_MK2_CAMO_IND_01", Hash: "0xC5E9AE52" },

    // Special Carbine Mk II
    { name: "Default Clip", Hash_Key: "COMPONENT_SPECIALCARBINE_MK2_CLIP_01", Hash: "0x16C69281" },
    { name: "Extended Clip", Hash_Key: "COMPONENT_SPECIALCARBINE_MK2_CLIP_02", Hash: "0xDE1FA12C" },
    { name: "Tracer Rounds", Hash_Key: "COMPONENT_SPECIALCARBINE_MK2_CLIP_TRACER", Hash: "0x8765C68A" },
    { name: "Incendiary Rounds", Hash_Key: "COMPONENT_SPECIALCARBINE_MK2_CLIP_INCENDIARY", Hash: "0xDE011286" },
    { name: "Armor Piercing Rounds", Hash_Key: "COMPONENT_SPECIALCARBINE_MK2_CLIP_ARMORPIERCING", Hash: "0x51351635" },
    { name: "Full Metal Jacket Rounds", Hash_Key: "COMPONENT_SPECIALCARBINE_MK2_CLIP_FMJ", Hash: "0x503DEA90" },
    { name: "Flashlight", Hash_Key: "COMPONENT_AT_AR_FLSH", Hash: "0x7BC4CDDC" },
    { name: "Holographic Sight", Hash_Key: "COMPONENT_AT_SIGHTS", Hash: "0x420FD713" },
    { name: "Small Scope", Hash_Key: "COMPONENT_AT_SCOPE_MACRO_MK2", Hash: "0x49B2945" },
    { name: "Medium Scope", Hash_Key: "COMPONENT_AT_SCOPE_MEDIUM_MK2", Hash: "0xC66B6542" },
    { name: "Suppressor", Hash_Key: "COMPONENT_AT_AR_SUPP_02", Hash: "0xA73D4664" },
    { name: "Flat Muzzle Brake", Hash_Key: "COMPONENT_AT_MUZZLE_01", Hash: "0xB99402D4" },
    { name: "Tactical Muzzle Brake", Hash_Key: "COMPONENT_AT_MUZZLE_02", Hash: "0xC867A07B" },
    { name: "Fat-End Muzzle Brake", Hash_Key: "COMPONENT_AT_MUZZLE_03", Hash: "0xDE11CBCF" },
    { name: "Precision Muzzle Brake", Hash_Key: "COMPONENT_AT_MUZZLE_04", Hash: "0xEC9068CC" },
    { name: "Heavy Duty Muzzle Brake", Hash_Key: "COMPONENT_AT_MUZZLE_05", Hash: "0x2E7957A" },
    { name: "Slanted Muzzle Brake", Hash_Key: "COMPONENT_AT_MUZZLE_06", Hash: "0x347EF8AC" },
    { name: "Split-End Muzzle Brake", Hash_Key: "COMPONENT_AT_MUZZLE_07", Hash: "0x4DB62ABE" },
    { name: "Grip", Hash_Key: "COMPONENT_AT_AR_AFGRIP_02", Hash: "0x9D65907A" },
    { name: "Default Barrel", Hash_Key: "COMPONENT_AT_SC_BARREL_01", Hash: "0xE73653A9" },
    { name: "Heavy Barrel", Hash_Key: "COMPONENT_AT_SC_BARREL_02", Hash: "0xF97F783B" },
    { name: "Digital Camo", Hash_Key: "COMPONENT_SPECIALCARBINE_MK2_CAMO", Hash: "0xD40BB53B" },
    { name: "Brushstroke Camo", Hash_Key: "COMPONENT_SPECIALCARBINE_MK2_CAMO_02", Hash: "0x431B238B" },
    { name: "Woodland Camo", Hash_Key: "COMPONENT_SPECIALCARBINE_MK2_CAMO_03", Hash: "0x34CF86F4" },
    { name: "Skull", Hash_Key: "COMPONENT_SPECIALCARBINE_MK2_CAMO_04", Hash: "0xB4C306DD" },
    { name: "Sessanta Nove", Hash_Key: "COMPONENT_SPECIALCARBINE_MK2_CAMO_05", Hash: "0xEE677A25" },
    { name: "Perseus", Hash_Key: "COMPONENT_SPECIALCARBINE_MK2_CAMO _06", Hash: "0xDF90DC78" },
    { name: "Leopard", Hash_Key: "COMPONENT_SPECIALCARBINE_MK2_CAMO_07", Hash: "0xA4C31EE" },
    { name: "Zebra", Hash_Key: "COMPONENT_SPECIALCARBINE_MK2_CAMO_08", Hash: "0x89CFB0F7" },
    { name: "Geometric", Hash_Key: "COMPONENT_SPECIALCARBINE_MK2_CAMO_09", Hash: "0x7B82145C" },
    { name: "Boom!", Hash_Key: "COMPONENT_SPECIALCARBINE_MK2_CAMO_10", Hash: "0x899CAF75" },
    { name: "Patriotic", Hash_Key: "COMPONENT_SPECIALCARBINE_MK2_CAMO_IND_01", Hash: "0x5218C819" },



    // Carbine Rifle Mk II
    { name: "Default Clip", Hash_Key: "COMPONENT_CARBINERIFLE_MK2_CLIP_01", Hash: "0x4C7A391E" },
    { name: "Extended Clip", Hash_Key: "COMPONENT_CARBINERIFLE_MK2_CLIP_02", Hash: "0x5DD5DBD5" },
    { name: "Tracer Rounds", Hash_Key: "COMPONENT_CARBINERIFLE_MK2_CLIP_TRACER", Hash: "0x1757F566" },
    { name: "Incendiary Rounds", Hash_Key: "COMPONENT_CARBINERIFLE_MK2_CLIP_INCENDIARY", Hash: "0x3D25C2A7" },
    { name: "Armor Piercing Rounds", Hash_Key: "COMPONENT_CARBINERIFLE_MK2_CLIP_ARMORPIERCING", Hash: "0x255D5D57" },
    { name: "Full Metal Jacket Rounds", Hash_Key: "COMPONENT_CARBINERIFLE_MK2_CLIP_FMJ", Hash: "0x44032F11" },
    { name: "Grip", Hash_Key: "COMPONENT_AT_AR_AFGRIP_02", Hash: "0x9D65907A" },
    { name: "Flashlight", Hash_Key: "COMPONENT_AT_AR_FLSH", Hash: "0x7BC4CDDC" },
    { name: "Holographic Sight", Hash_Key: "COMPONENT_AT_SIGHTS", Hash: "0x420FD713" },
    { name: "Small Scope", Hash_Key: "COMPONENT_AT_SCOPE_MACRO_MK2", Hash: "0x49B2945" },
    { name: "Medium Scope", Hash_Key: "COMPONENT_AT_SCOPE_MEDIUM_MK2", Hash: "0xC66B6542" },
    { name: "Suppressor", Hash_Key: "COMPONENT_AT_AR_SUPP", Hash: "0x837445AA" },
    { name: "Flat Muzzle Brake", Hash_Key: "COMPONENT_AT_MUZZLE_01", Hash: "0xB99402D4" },
    { name: "Tactical Muzzle Brake", Hash_Key: "COMPONENT_AT_MUZZLE_02", Hash: "0xC867A07B" },
    { name: "Fat-End Muzzle Brake", Hash_Key: "COMPONENT_AT_MUZZLE_03", Hash: "0xDE11CBCF" },
    { name: "Precision Muzzle Brake", Hash_Key: "COMPONENT_AT_MUZZLE_04", Hash: "0xEC9068CC" },
    { name: "Heavy Duty Muzzle Brake", Hash_Key: "COMPONENT_AT_MUZZLE_05", Hash: "0x2E7957A" },
    { name: "Slanted Muzzle Brake", Hash_Key: "COMPONENT_AT_MUZZLE_06", Hash: "0x347EF8AC" },
    { name: "Split-End Muzzle Brake", Hash_Key: "COMPONENT_AT_MUZZLE_07", Hash: "0x4DB62ABE" },
    { name: "Default Barrel", Hash_Key: "COMPONENT_AT_CR_BARREL_01", Hash: "0x833637FF" },
    { name: "Heavy Barrel", Hash_Key: "COMPONENT_AT_CR_BARREL_02", Hash: "0x8B3C480B" },
    { name: "Digital Camo", Hash_Key: "COMPONENT_CARBINERIFLE_MK2_CAMO", Hash: "0x4BDD6F16" },
    { name: "Brushstroke Camo", Hash_Key: "COMPONENT_CARBINERIFLE_MK2_CAMO_02", Hash: "0x406A7908" },
    { name: "Woodland Camo", Hash_Key: "COMPONENT_CARBINERIFLE_MK2_CAMO_03", Hash: "0x2F3856A4" },
    { name: "Skull", Hash_Key: "COMPONENT_CARBINERIFLE_MK2_CAMO_04", Hash: "0xE50C424D" },
    { name: "Sessanta Nove", Hash_Key: "COMPONENT_CARBINERIFLE_MK2_CAMO_05", Hash: "0xD37D1F2F" },
    { name: "Perseus", Hash_Key: "COMPONENT_CARBINERIFLE_MK2_CAMO_06", Hash: "0 x86268483" },
    { name: "Leopard", Hash_Key: "COMPONENT_CARBINERIFLE_MK2_CAMO_07", Hash: "0xF420E076" },
    { name: "Zebra", Hash_Key: "COMPONENT_CARBINERIFLE_MK2_CAMO_08", Hash: "0xAAE14DF8" },
    { name: "Geometric", Hash_Key: "COMPONENT_CARBINERIFLE_MK2_CAMO_09", Hash: "0x9893A95D" },
    { name: "Boom!", Hash_Key: "COMPONENT_CARBINERIFLE_MK2_CAMO_10", Hash: "0x6B13CD3E" },
    { name: "Patriotic", Hash_Key: "COMPONENT_CARBINERIFLE_MK2_CAMO_IND_01", Hash: "0xDA55CD3F" },





    // Sniper Rifle
    { name: "Default Clip", Hash_Key: "COMPONENT_SNIPERRIFLE_CLIP_01", Hash: "0x9BC64089" },
    { name: "Suppressor", Hash_Key: "COMPONENT_AT_AR_SUPP_02", Hash: "0xA73D4664" },
    { name: "Scope", Hash_Key: "COMPONENT_AT_SCOPE_LARGE", Hash: "0xD2443DDC" },
    { name: "Advanced Scope", Hash_Key: "COMPONENT_AT_SCOPE_MAX", Hash: "0xBC54DA77" },
    { name: "Etched Wood Grip Finish", Hash_Key: "COMPONENT_SNIPERRIFLE_VARMOD_LUXE", Hash: "0x4032B5E7" },

    // Heavy Sniper
    { name: "Default Clip", Hash_Key: "COMPONENT_HEAVYSNIPER_CLIP_01", Hash: "0x476F52F4" },
    { name: "Scope", Hash_Key: "COMPONENT_AT_SCOPE_LARGE", Hash: "0xD2443DDC" },
    { name: "Advanced Scope", Hash_Key: "COMPONENT_AT_SCOPE_MAX", Hash: "0xBC54DA77" },

    // Marksman Rifle Mk II
    { name: "Default Clip", Hash_Key: "COMPONENT_MARKSMANRIFLE_MK2_CLIP_01", Hash: "0x94E12DCE" },
    { name: "Extended Clip", Hash_Key: "COMPONENT_MARKSMANRIFLE_MK2_CLIP_02", Hash: "0xE6CFD1AA" },
    { name: "Tracer Rounds", Hash_Key: "COMPONENT_MARKSMANRIFLE_MK2_CLIP_TRACER", Hash: "0xD77A22D2" },
    { name: "Incendiary Rounds", Hash_Key: "COMPONENT_MARKSMANRIFLE_MK2_CLIP_INCENDIARY", Hash: "0x6DD7A86E" },
    { name: "Armor Piercing Rounds", Hash_Key: "COMPONENT_MARKSMANRIFLE_MK2_CLIP_ARMORPIERCING", Hash: "0xF46FD079" },
    { name: "Full Metal Jacket Rounds", Hash_Key: "COMPONENT_MARKSMANRIFLE_MK2_CLIP_FMJ", Hash: "0xE14A9ED3" },
    { name: "Holographic Sight", Hash_Key: "COMPONENT_AT_SIGHTS", Hash: "0x420FD713" },
    { name: "Large Scope", Hash_Key: "COMPONENT_AT_SCOPE_MEDIUM_MK2", Hash: "0xC66B6542" },
    { name: "Zoom Scope", Hash_Key: "COMPONENT_AT_SCOPE_LARGE_FIXED_ZOOM_MK2", Hash: "0x5B1C713C" },
    { name: "Flashlight", Hash_Key: "COMPONENT_AT_AR_FLSH", Hash: "0x7BC4CDDC" },
    { name: "Suppressor", Hash_Key: "COMPONENT_AT_AR_SUPP", Hash: "0x837445AA" },
    { name: "Flat Muzzle Brake", Hash_Key: "COMPONENT_AT_MUZZLE_01", Hash: "0xB99402D4" },
    { name: "Tactical Muzzle Brake", Hash_Key: "COMPONENT_AT_MUZZLE_02", Hash: "0xC867A07B" },
    { name: "Fat-End Muzzle Brake", Hash_Key: "COMPONENT_AT_MUZZLE_03", Hash: "0xDE11CBCF" },
    { name: "Precision Muzzle Brake", Hash_Key: "COMPONENT_AT_MUZZLE_04", Hash: "0xEC9068CC" },
    { name: "Heavy Duty Muzzle Brake", Hash_Key: "COMPONENT_AT_MUZZLE_05", Hash: "0x2E7957A" },
    { name: "Slanted Muzzle Brake", Hash_Key: "COMPONENT_AT_MUZZLE_06", Hash: "0x347EF8AC" },
    { name: "Split-End Muzzle Brake", Hash_Key: "COMPONENT_AT_MUZZLE_07", Hash: "0x4DB62ABE" },
    { name: "Default Barrel", Hash_Key: "COMPONENT_AT_MRFL_BARREL_01", Hash: "0x381B5D89" },
    { name: "Heavy Barrel", Hash_Key: "COMPONENT_AT_MRFL_BARREL_02", Hash: "0x68373DDC" },
    { name: "Grip", Hash_Key: "COMPONENT_AT_AR_AFGRIP_02", Hash: "0x9D65907A" },
    { name: "Digital Camo", Hash_Key: "COMPONENT_MARKSMANRIFLE_MK2_CAMO", Hash: "0x9094FBA0" },
    { name: "Brushstroke Camo", Hash_Key: "COMPONENT_MARKSMANRIFLE_MK2_CAMO_02", Hash: "0x7320F4B2" },
    { name: "Woodland Camo", Hash_Key: "COMPONENT_MARKSMANRIFLE_MK2_CAMO_03", Hash: "0x60CF500F" },
    { name: "Skull", Hash_Key: "COMPONENT_MARKSMANRIFLE_MK2_CAMO_04", Hash: "0xFE668B3F" },
    { name: "Sessanta Nove", Hash_Key: "COMPONENT_MARKSMANRIFLE_MK2_CAMO_ 05", Hash: "0xF3757559" },
    { name: "Perseus", Hash_Key: "COMPONENT_MARKSMANRIFLE_MK2_CAMO_06", Hash: "0x193B40E8" },
    { name: "Leopard", Hash_Key: "COMPONENT_MARKSMANRIFLE_MK2_CAMO_07", Hash: "0x107D2F6C" },
    { name: "Zebra", Hash_Key: "COMPONENT_MARKSMANRIFLE_MK2_CAMO_08", Hash: "0xC4E91841" },
    { name: "Geometric", Hash_Key: "COMPONENT_MARKSMANRIFLE_MK2_CAMO_09", Hash: "0x9BB1C5D3" },
    { name: "Boom!", Hash_Key: "COMPONENT_MARKSMANRIFLE_MK2_CAMO_10", Hash: "0x3B61040B" },
    { name: "Patriotic", Hash_Key: "COMPONENT_MARKSMANRIFLE_MK2_CAMO_IND_01", Hash: "0xB7A316DA" },

    // Heavy Sniper Mk II
    { name: "Default Clip", Hash_Key: "COMPONENT_HEAVYSNIPER_MK2_CLIP_01", Hash: "0xFA1E1A28" },
    { name: "Extended Clip", Hash_Key: "COMPONENT_HEAVYSNIPER_MK2_CLIP_02", Hash: "0x2CD8FF9D" },
    { name: "Incendiary Rounds", Hash_Key: "COMPONENT_HEAVYSNIPER_MK2_CLIP_INCENDIARY", Hash: "0xEC0F617" },
    { name: "Armor Piercing Rounds", Hash_Key: "COMPONENT_HEAVYSNIPER_MK2_CLIP_ARMORPIERCING", Hash: "0xF835D6D4" },
    { name: "Full Metal Jacket Rounds", Hash_Key: "COMPONENT_HEAVYSNIPER_MK2_CLIP_FMJ", Hash: "0x3BE948F6" },
    { name: "Explosive Rounds", Hash_Key: "COMPONENT_HEAVYSNIPER_MK2_CLIP_EXPLOSIVE", Hash: "0x89EBDAA7" },
    { name: "Zoom Scope", Hash_Key: "COMPONENT_AT_SCOPE_LARGE_MK2", Hash: "0x82C10383" },
    { name: "Advanced Scope", Hash_Key: "COMPONENT_AT_SCOPE_MAX", Hash: "0xBC54DA77" },
    { name: "Night Vision Scope", Hash_Key: "COMPONENT_AT_SCOPE_NV", Hash: "0xB68010B0" },
    { name: "Thermal Scope", Hash_Key: "COMPONENT_AT_SCOPE_THERMAL", Hash: "0x2E43DA41" },
    { name: "Suppressor", Hash_Key: "COMPONENT_AT_SR_SUPP_03", Hash: "0xAC42DF71" },
    { name: "Squared Muzzle Brake", Hash_Key: "COMPONENT_AT_MUZZLE_08", Hash: "0x5F7DCE4D" },
    { name: "Bell-End Muzzle Brake", Hash_Key: "COMPONENT_AT_MUZZLE_09", Hash: "0x6927E1A1" },
    { name: "Default Barrel", Hash_Key: "COMPONENT_AT_SR_BARREL_01", Hash: "0x909630B7" },
    { name: "Heavy Barrel", Hash_Key: "COMPONENT_AT_SR_BARREL_02", Hash: "0x108AB09E" },
    { name: "Digital Camo", Hash_Key: "COMPONENT_HEAVYSNIPER_MK2_CAMO", Hash: "0xF8337D02" },
    { name: "Brushstroke Camo", Hash_Key: "COMPONENT_HEAVYSNIPER_MK2_CAMO_02", Hash: "0xC5BEDD65" },
    { name: "Woodland Camo", Hash_Key: "COMPONENT_HEAVYSNIPER_MK2_CAMO_03", Hash: "0xE9712475" },
    { name: "Skull", Hash_Key: "COMPONENT_HEAVYSNIPER_MK2_CAMO_04", Hash: "0x13AA78E7" },
    { name: "Sessanta Nove", Hash_Key: "COMPONENT_HEAVYSNIPER_MK2_CAMO_05", Hash: "0x26591E50" },
    { name: "Perseus", Hash_Key: "COMPONENT_HEAVYSNIPER_MK2_CAMO_06", Hash: "0x302731EC" },
    { name: "Leopard", Hash_Key: "COMPONENT_HEAVYSNIPER_MK2_CAMO_07", Hash: "0xAC722A78" },
    { name: "Zebra", Hash_Key: "COMPONENT_HEAVYSNIPER_MK2_CAMO_08", Hash: "0xBEA4CEDD" },
    { name: "Geometric", Hash_Key: "COMPONENT_HEAVYSNIPER_MK2_CAMO_09", Hash: "0xCD776C82" },
    { name: "Boom!", Hash_Key: "COMPONENT_HEAVYSNIPER_MK2_CAMO_10", Hash: "0xABC5ACC7" },
    { name: "Patriotic", Hash_Key: " COMPONENT_HEAVYSNIPER_MK2_CAMO_IND_01", Hash: "0x6C32D2EB" },

    // Marksman Rifle
    { name: "Default Clip", Hash_Key: "COMPONENT_MARKSMANRIFLE_CLIP_01", Hash: "0xD83B4141" },
    { name: "Extended Clip", Hash_Key: "COMPONENT_MARKSMANRIFLE_CLIP_02", Hash: "0xCCFD2AC5" },
    { name: "Scope", Hash_Key: "COMPONENT_AT_SCOPE_LARGE_FIXED_ZOOM", Hash: "0x1C221B1A" },
    { name: "Flashlight", Hash_Key: "COMPONENT_AT_AR_FLSH", Hash: "0x7BC4CDDC" },
    { name: "Suppressor", Hash_Key: "COMPONENT_AT_AR_SUPP", Hash: "0x837445AA" },
    { name: "Grip", Hash_Key: "COMPONENT_AT_AR_AFGRIP", Hash: "0xC164F53" },
    { name: "Yusuf Amir Luxury Finish", Hash_Key: "COMPONENT_MARKSMANRIFLE_VARMOD_LUXE", Hash: "0x161E9241" },

    // Grenade Launcher
    { name: "Default Clip", Hash_Key: "COMPONENT_GRENADELAUNCHER_CLIP_01", Hash: "0x11AE5C97" },
    { name: "Flashlight", Hash_Key: "COMPONENT_AT_AR_FLSH", Hash: "0x7BC4CDDC" },
    { name: "Grip", Hash_Key: "COMPONENT_AT_AR_AFGRIP", Hash: "0xC164F53" },
    { name: "Scope", Hash_Key: "COMPONENT_AT_SCOPE_SMALL", Hash: "0xAA2C45B4" }
]